In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import sparse

一阶微分算符

In [31]:
N=10
dx=1
(np.diag(np.ones((N-1), np.float32), 1)
 - np.diag(np.ones((N-1), np.float32), -1))/(2*dx)

array([[ 0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [-0.5,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. , -0.5,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. , -0.5,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , -0.5,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. , -0.5,  0. ,  0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. , -0.5,  0. ,  0.5,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. , -0.5,  0. ,  0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , -0.5,  0. ,  0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , -0.5,  0. ]],
      dtype=float32)

二阶微分算符

In [6]:
N=10
dx=1
(-2 * np.diag(np.ones((N), np.float32), 0)
            + np.diag(np.ones((N-1), np.float32), 1)
            + np.diag(np.ones((N-1), np.float32), -1))/(dx**2)

array([[-2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -2.]], dtype=float32)

scipy稀疏矩阵的几个函数

In [4]:
sparse.diags(np.ones((N), np.float32), 0)#生成对角阵
sparse.identity(4)#生成单位阵

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements (1 diagonals) in DIAgonal format>

波函数向量形式
$$
|\Psi(t)\rangle=\left(\begin{array}{c}
\Psi\left(x_{1}\right) \\
\Psi\left(x_{2}\right) \\
\Psi\left(x_{3}\right) \\
\ldots \\
\Psi\left(x_{n}\right)
\end{array}\right)_{t}
$$

In [10]:
def psi(t=0):
    return 0

In [11]:
psi()

0

矩阵乘法

In [26]:
k = np.linspace(0, 4, 5)
np.diag(k*k, 0)


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  4.,  0.,  0.],
       [ 0.,  0.,  0.,  9.,  0.],
       [ 0.,  0.,  0.,  0., 16.]])

In [32]:
np.dot((np.diag(np.ones((5-1), np.float32), 1)
 - np.diag(np.ones((5-1), np.float32), -1))/(2*dx),k)

array([ 0.5,  1. ,  1. ,  1. , -1.5])

In [47]:
display(k.reshape(5,1))

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.]])

In [44]:
np.conjugate(k)#共轭
k

array([0., 1., 2., 3., 4.])

In [49]:
k*k.reshape(5,1)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.],
       [ 0.,  4.,  8., 12., 16.]])

In [50]:
k.reshape(5,1)*k

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.],
       [ 0.,  4.,  8., 12., 16.]])

In [53]:
np.dot(k,k)

30.0

In [61]:
np.dot(k,k.reshape(5,1))

array([30.])

In [60]:
np.dot(k.reshape(5,1),k)

ValueError: shapes (5,1) and (5,) not aligned: 1 (dim 1) != 5 (dim 0)

In [59]:
np.dot(k,k)

30.0